name: Build

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build package
        run: |
          set -ex
          mkdir output
          podman run --name=builder -di -v ./cromite.spec:/cromite.spec -v ./output:/output quay.io/rockylinux/rockylinux:9
          podman exec builder dnf groupinstall "RPM Development Tools" -y
          podman exec builder rpmdev-setuptree
          podman exec builder cp /cromite.spec /root/rpmbuild/SPECS/cromite.spec
          podman exec builder bash -c "cat /root/rpmbuild/SPECS/cromite.spec | grep BuildRequires | cut -f2 -d: | xargs dnf install --allowerasing -y"
          podman exec builder spectool -gR /root/rpmbuild/SPECS/cromite.spec
          podman exec builder rpmbuild --nocheck -bb /root/rpmbuild/SPECS/cromite.spec
          podman exec builder bash -c 'cp /root/rpmbuild/RPMS/*/*.rpm /output/output.rpm'
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: continuous
          name: Continuous
          files: |
            output/output.rpm
